version: '3.4'

services:
  client:
    image: client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        BASE_URL: https://sma-library.duckdns.org/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
  server:
    image: server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        BASE_URL: https://sma-library.duckdns.org/api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Manila
      - PORT=5000
      - MONGO_URI=mongodb://username:password@mongodb:27017/admin
      - SESSION_SECRET=tu8861sRFQyXDRH
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db